### ISSUE TITLE
Invalid URL for blog post on touchpad‐toggle Wiki page

### ISSUE THREAD

**Issue by C-Duv** [yktoo/yktools#1]
Wiki page for [touchpad‐toggle](https://github.com/yktoo/yktools/wiki/touchpad%E2%80%90toggle) has a link to the related blog post of Yyktoo blog.

But it's URL is invalid, it's `https://yktoo.com/blog/post/305` and once accessed displays a "_Page not found._".

It seem the correct URL is the following https://yktoo.com/en/blog/post/2017/01/17-touchpad-toggle-script-for-ubuntu/ ("_Touchpad toggle script for Ubuntu_").

**Comment by yktoo** [comment]
Thanks @C-Duv, the link is fixed (as well as another one).
