### ISSUE TITLE
site links broken when lang missing

### ISSUE THREAD

**Issue by birbilis** [yktoo/yktools#2]
readme.md mentions
https://yktoo.com/software/yktools/
but correct is
https://yktoo.com/en/software/yktools/

probably other links for other repos of yours too due to this

I'd suggest autoredirecting on server to en language if a link doesn't have it (as long as all links exist for en)

**Comment by yktoo** [comment]
Thanks @birbilis for reporting this, links are fixed now. Automatic redirection would make sense, but unfortunately [yktoo.com](https://yktoo.com/) is a static website with pre-generated pages (more on that [here](https://yktoo.com/en/blog/post/2019/08/23-the-yktoo.com-website-code-goes-public/)), so automation options are pretty limited.
